begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|junit
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|Serializable
import|;
end_import

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|URI
import|;
end_import

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|URISyntaxException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|BytesMessage
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|Connection
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|JMSException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|MapMessage
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|Message
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|MessageProducer
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|ObjectMessage
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|Session
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|StreamMessage
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|TextMessage
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|ActiveMQConnectionFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|broker
operator|.
name|BrokerFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|broker
operator|.
name|BrokerPlugin
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|broker
operator|.
name|BrokerService
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|broker
operator|.
name|region
operator|.
name|Destination
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|broker
operator|.
name|region
operator|.
name|policy
operator|.
name|PolicyEntry
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|broker
operator|.
name|region
operator|.
name|policy
operator|.
name|PolicyMap
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|command
operator|.
name|ActiveMQDestination
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|plugin
operator|.
name|StatisticsBrokerPlugin
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|pool
operator|.
name|PooledConnectionFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|rules
operator|.
name|ExternalResource
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|Logger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|LoggerFactory
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|command
operator|.
name|ActiveMQDestination
operator|.
name|QUEUE_TYPE
import|;
end_import

begin_comment
comment|/**  * A JUnit Rule that embeds an ActiveMQ broker into a test.  */
end_comment

begin_class
specifier|public
class|class
name|EmbeddedActiveMQBroker
extends|extends
name|ExternalResource
block|{
name|Logger
name|log
init|=
name|LoggerFactory
operator|.
name|getLogger
argument_list|(
name|this
operator|.
name|getClass
argument_list|()
argument_list|)
decl_stmt|;
name|BrokerService
name|brokerService
decl_stmt|;
name|InternalClient
name|internalClient
decl_stmt|;
comment|/**      * Create an embedded ActiveMQ broker using defaults      *<p>      * The defaults are:      * - the broker name is 'embedded-broker'      * - JMX is disabled      * - Persistence is disabled      */
specifier|public
name|EmbeddedActiveMQBroker
parameter_list|()
block|{
name|brokerService
operator|=
operator|new
name|BrokerService
argument_list|()
expr_stmt|;
name|brokerService
operator|.
name|setUseJmx
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|brokerService
operator|.
name|setUseShutdownHook
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|brokerService
operator|.
name|setPersistent
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|brokerService
operator|.
name|setBrokerName
argument_list|(
literal|"embedded-broker"
argument_list|)
expr_stmt|;
block|}
comment|/**      * Create an embedded ActiveMQ broker using a configuration URI      */
specifier|public
name|EmbeddedActiveMQBroker
parameter_list|(
name|String
name|configurationURI
parameter_list|)
block|{
try|try
block|{
name|brokerService
operator|=
name|BrokerFactory
operator|.
name|createBroker
argument_list|(
name|configurationURI
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Exception
name|ex
parameter_list|)
block|{
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"Exception encountered creating embedded ActiveMQ broker from configuration URI: "
operator|+
name|configurationURI
argument_list|,
name|ex
argument_list|)
throw|;
block|}
block|}
comment|/**      * Create an embedded ActiveMQ broker using a configuration URI      */
specifier|public
name|EmbeddedActiveMQBroker
parameter_list|(
name|URI
name|configurationURI
parameter_list|)
block|{
try|try
block|{
name|brokerService
operator|=
name|BrokerFactory
operator|.
name|createBroker
argument_list|(
name|configurationURI
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Exception
name|ex
parameter_list|)
block|{
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"Exception encountered creating embedded ActiveMQ broker from configuration URI: "
operator|+
name|configurationURI
argument_list|,
name|ex
argument_list|)
throw|;
block|}
block|}
specifier|public
specifier|static
name|void
name|setMessageProperties
parameter_list|(
name|Message
name|message
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|properties
parameter_list|)
block|{
if|if
condition|(
name|properties
operator|!=
literal|null
operator|&&
name|properties
operator|.
name|size
argument_list|()
operator|>
literal|0
condition|)
block|{
for|for
control|(
name|Map
operator|.
name|Entry
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|property
range|:
name|properties
operator|.
name|entrySet
argument_list|()
control|)
block|{
try|try
block|{
name|message
operator|.
name|setObjectProperty
argument_list|(
name|property
operator|.
name|getKey
argument_list|()
argument_list|,
name|property
operator|.
name|getValue
argument_list|()
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|JMSException
name|jmsEx
parameter_list|)
block|{
throw|throw
operator|new
name|EmbeddedActiveMQBrokerException
argument_list|(
name|String
operator|.
name|format
argument_list|(
literal|"Failed to set property {%s = %s}"
argument_list|,
name|property
operator|.
name|getKey
argument_list|()
argument_list|,
name|property
operator|.
name|getValue
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
argument_list|,
name|jmsEx
argument_list|)
throw|;
block|}
block|}
block|}
block|}
comment|/**      * Customize the configuration of the embedded ActiveMQ broker      *<p>      * This method is called before the embedded ActiveMQ broker is started, and can      * be overridden to this method to customize the broker configuration.      */
specifier|protected
name|void
name|configure
parameter_list|()
block|{     }
comment|/**      * Start the embedded ActiveMQ broker, blocking until the broker has successfully started.      *<p/>      * The broker will normally be started by JUnit using the before() method.  This method allows the broker to      * be started manually to support advanced testing scenarios.      */
specifier|public
name|void
name|start
parameter_list|()
block|{
try|try
block|{
name|this
operator|.
name|configure
argument_list|()
expr_stmt|;
name|brokerService
operator|.
name|start
argument_list|()
expr_stmt|;
name|internalClient
operator|=
operator|new
name|InternalClient
argument_list|()
expr_stmt|;
name|internalClient
operator|.
name|start
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Exception
name|ex
parameter_list|)
block|{
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"Exception encountered starting embedded ActiveMQ broker: {}"
operator|+
name|this
operator|.
name|getBrokerName
argument_list|()
argument_list|,
name|ex
argument_list|)
throw|;
block|}
name|brokerService
operator|.
name|waitUntilStarted
argument_list|()
expr_stmt|;
block|}
comment|/**      * Stop the embedded ActiveMQ broker, blocking until the broker has stopped.      *<p/>      * The broker will normally be stopped by JUnit using the after() method.  This method allows the broker to      * be stopped manually to support advanced testing scenarios.      */
specifier|public
name|void
name|stop
parameter_list|()
block|{
if|if
condition|(
name|internalClient
operator|!=
literal|null
condition|)
block|{
name|internalClient
operator|.
name|stop
argument_list|()
expr_stmt|;
name|internalClient
operator|=
literal|null
expr_stmt|;
block|}
if|if
condition|(
operator|!
name|brokerService
operator|.
name|isStopped
argument_list|()
condition|)
block|{
try|try
block|{
name|brokerService
operator|.
name|stop
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Exception
name|ex
parameter_list|)
block|{
name|log
operator|.
name|warn
argument_list|(
literal|"Exception encountered stopping embedded ActiveMQ broker: {}"
operator|+
name|this
operator|.
name|getBrokerName
argument_list|()
argument_list|,
name|ex
argument_list|)
expr_stmt|;
block|}
block|}
name|brokerService
operator|.
name|waitUntilStopped
argument_list|()
expr_stmt|;
block|}
comment|/**      * Start the embedded ActiveMQ Broker      *<p/>      * Invoked by JUnit to setup the resource      */
annotation|@
name|Override
specifier|protected
name|void
name|before
parameter_list|()
throws|throws
name|Throwable
block|{
name|log
operator|.
name|info
argument_list|(
literal|"Starting embedded ActiveMQ broker: {}"
argument_list|,
name|this
operator|.
name|getBrokerName
argument_list|()
argument_list|)
expr_stmt|;
name|this
operator|.
name|start
argument_list|()
expr_stmt|;
name|super
operator|.
name|before
argument_list|()
expr_stmt|;
block|}
comment|/**      * Stop the embedded ActiveMQ Broker      *<p/>      * Invoked by JUnit to tear down the resource      */
annotation|@
name|Override
specifier|protected
name|void
name|after
parameter_list|()
block|{
name|log
operator|.
name|info
argument_list|(
literal|"Stopping Embedded ActiveMQ Broker: {}"
argument_list|,
name|this
operator|.
name|getBrokerName
argument_list|()
argument_list|)
expr_stmt|;
name|super
operator|.
name|after
argument_list|()
expr_stmt|;
name|this
operator|.
name|stop
argument_list|()
expr_stmt|;
block|}
comment|/**      * Create an ActiveMQConnectionFactory for the embedded ActiveMQ Broker      *      * @return a new ActiveMQConnectionFactory      */
specifier|public
name|ActiveMQConnectionFactory
name|createConnectionFactory
parameter_list|()
block|{
name|ActiveMQConnectionFactory
name|connectionFactory
init|=
operator|new
name|ActiveMQConnectionFactory
argument_list|()
decl_stmt|;
name|connectionFactory
operator|.
name|setBrokerURL
argument_list|(
name|getVmURL
argument_list|()
argument_list|)
expr_stmt|;
return|return
name|connectionFactory
return|;
block|}
comment|/**      * Create an PooledConnectionFactory for the embedded ActiveMQ Broker      *      * @return a new PooledConnectionFactory      */
specifier|public
name|PooledConnectionFactory
name|createPooledConnectionFactory
parameter_list|()
block|{
name|ActiveMQConnectionFactory
name|connectionFactory
init|=
name|createConnectionFactory
argument_list|()
decl_stmt|;
name|PooledConnectionFactory
name|pooledConnectionFactory
init|=
operator|new
name|PooledConnectionFactory
argument_list|(
name|connectionFactory
argument_list|)
decl_stmt|;
return|return
name|pooledConnectionFactory
return|;
block|}
comment|/**      * Get the BrokerService for the embedded ActiveMQ broker.      *<p/>      * This may be required for advanced configuration of the BrokerService.      *      * @return the embedded ActiveMQ broker      */
specifier|public
name|BrokerService
name|getBrokerService
parameter_list|()
block|{
return|return
name|brokerService
return|;
block|}
comment|/**      * Get the failover VM URL for the embedded ActiveMQ Broker      *<p/>      * NOTE:  The create=false option is appended to the URL to avoid the automatic creation of brokers      * and the resulting duplicate broker errors      *      * @return the VM URL for the embedded broker      */
specifier|public
name|String
name|getVmURL
parameter_list|()
block|{
return|return
name|getVmURL
argument_list|(
literal|true
argument_list|)
return|;
block|}
comment|/**      * Get the VM URL for the embedded ActiveMQ Broker      *<p/>      * NOTE:  The create=false option is appended to the URL to avoid the automatic creation of brokers      * and the resulting duplicate broker errors      *      * @param failoverURL if true a failover URL will be returned      * @return the VM URL for the embedded broker      */
specifier|public
name|String
name|getVmURL
parameter_list|(
name|boolean
name|failoverURL
parameter_list|)
block|{
if|if
condition|(
name|failoverURL
condition|)
block|{
return|return
name|String
operator|.
name|format
argument_list|(
literal|"failover:(%s?create=false)"
argument_list|,
name|brokerService
operator|.
name|getVmConnectorURI
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
return|;
block|}
return|return
name|brokerService
operator|.
name|getVmConnectorURI
argument_list|()
operator|.
name|toString
argument_list|()
operator|+
literal|"?create=false"
return|;
block|}
comment|/**      * Get the failover VM URI for the embedded ActiveMQ Broker      *<p/>      * NOTE:  The create=false option is appended to the URI to avoid the automatic creation of brokers      * and the resulting duplicate broker errors      *      * @return the VM URI for the embedded broker      */
specifier|public
name|URI
name|getVmURI
parameter_list|()
block|{
return|return
name|getVmURI
argument_list|(
literal|true
argument_list|)
return|;
block|}
comment|/**      * Get the VM URI for the embedded ActiveMQ Broker      *<p/>      * NOTE:  The create=false option is appended to the URI to avoid the automatic creation of brokers      * and the resulting duplicate broker errors      *      * @param failoverURI if true a failover URI will be returned      * @return the VM URI for the embedded broker      */
specifier|public
name|URI
name|getVmURI
parameter_list|(
name|boolean
name|failoverURI
parameter_list|)
block|{
name|URI
name|result
decl_stmt|;
try|try
block|{
name|result
operator|=
operator|new
name|URI
argument_list|(
name|getVmURL
argument_list|(
name|failoverURI
argument_list|)
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|URISyntaxException
name|uriEx
parameter_list|)
block|{
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"Unable to create failover URI"
argument_list|,
name|uriEx
argument_list|)
throw|;
block|}
return|return
name|result
return|;
block|}
comment|/**      * Get the name of the embedded ActiveMQ Broker      *      * @return name of the embedded broker      */
specifier|public
name|String
name|getBrokerName
parameter_list|()
block|{
return|return
name|brokerService
operator|.
name|getBrokerName
argument_list|()
return|;
block|}
specifier|public
name|void
name|setBrokerName
parameter_list|(
name|String
name|brokerName
parameter_list|)
block|{
name|brokerService
operator|.
name|setBrokerName
argument_list|(
name|brokerName
argument_list|)
expr_stmt|;
block|}
specifier|public
name|boolean
name|isStatisticsPluginEnabled
parameter_list|()
block|{
name|BrokerPlugin
index|[]
name|plugins
init|=
name|brokerService
operator|.
name|getPlugins
argument_list|()
decl_stmt|;
if|if
condition|(
literal|null
operator|!=
name|plugins
condition|)
block|{
for|for
control|(
name|BrokerPlugin
name|plugin
range|:
name|plugins
control|)
block|{
if|if
condition|(
name|plugin
operator|instanceof
name|StatisticsBrokerPlugin
condition|)
block|{
return|return
literal|true
return|;
block|}
block|}
block|}
return|return
literal|false
return|;
block|}
specifier|public
name|void
name|enableStatisticsPlugin
parameter_list|()
block|{
if|if
condition|(
operator|!
name|isStatisticsPluginEnabled
argument_list|()
condition|)
block|{
name|BrokerPlugin
index|[]
name|newPlugins
decl_stmt|;
name|BrokerPlugin
index|[]
name|currentPlugins
init|=
name|brokerService
operator|.
name|getPlugins
argument_list|()
decl_stmt|;
if|if
condition|(
literal|null
operator|!=
name|currentPlugins
operator|&&
literal|0
operator|<
name|currentPlugins
operator|.
name|length
condition|)
block|{
name|newPlugins
operator|=
operator|new
name|BrokerPlugin
index|[
name|currentPlugins
operator|.
name|length
operator|+
literal|1
index|]
expr_stmt|;
name|System
operator|.
name|arraycopy
argument_list|(
name|currentPlugins
argument_list|,
literal|0
argument_list|,
name|newPlugins
argument_list|,
literal|0
argument_list|,
name|currentPlugins
operator|.
name|length
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|newPlugins
operator|=
operator|new
name|BrokerPlugin
index|[
literal|1
index|]
expr_stmt|;
block|}
name|newPlugins
index|[
name|newPlugins
operator|.
name|length
operator|-
literal|1
index|]
operator|=
operator|new
name|StatisticsBrokerPlugin
argument_list|()
expr_stmt|;
name|brokerService
operator|.
name|setPlugins
argument_list|(
name|newPlugins
argument_list|)
expr_stmt|;
block|}
block|}
specifier|public
name|void
name|disableStatisticsPlugin
parameter_list|()
block|{
if|if
condition|(
name|isStatisticsPluginEnabled
argument_list|()
condition|)
block|{
name|BrokerPlugin
index|[]
name|currentPlugins
init|=
name|brokerService
operator|.
name|getPlugins
argument_list|()
decl_stmt|;
if|if
condition|(
literal|1
operator|<
name|currentPlugins
operator|.
name|length
condition|)
block|{
name|BrokerPlugin
index|[]
name|newPlugins
init|=
operator|new
name|BrokerPlugin
index|[
name|currentPlugins
operator|.
name|length
operator|-
literal|1
index|]
decl_stmt|;
name|int
name|i
init|=
literal|0
decl_stmt|;
for|for
control|(
name|BrokerPlugin
name|plugin
range|:
name|currentPlugins
control|)
block|{
if|if
condition|(
operator|!
operator|(
name|plugin
operator|instanceof
name|StatisticsBrokerPlugin
operator|)
condition|)
block|{
name|newPlugins
index|[
name|i
operator|++
index|]
operator|=
name|plugin
expr_stmt|;
block|}
block|}
name|brokerService
operator|.
name|setPlugins
argument_list|(
name|newPlugins
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|brokerService
operator|.
name|setPlugins
argument_list|(
literal|null
argument_list|)
expr_stmt|;
block|}
block|}
block|}
specifier|public
name|boolean
name|isAdvisoryForDeliveryEnabled
parameter_list|()
block|{
return|return
name|getDefaultPolicyEntry
argument_list|()
operator|.
name|isAdvisoryForDelivery
argument_list|()
return|;
block|}
specifier|public
name|void
name|enableAdvisoryForDelivery
parameter_list|()
block|{
name|getDefaultPolicyEntry
argument_list|()
operator|.
name|setAdvisoryForDelivery
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|disableAdvisoryForDelivery
parameter_list|()
block|{
name|getDefaultPolicyEntry
argument_list|()
operator|.
name|setAdvisoryForDelivery
argument_list|(
literal|false
argument_list|)
expr_stmt|;
block|}
specifier|public
name|boolean
name|isAdvisoryForConsumedEnabled
parameter_list|()
block|{
return|return
name|getDefaultPolicyEntry
argument_list|()
operator|.
name|isAdvisoryForConsumed
argument_list|()
return|;
block|}
specifier|public
name|void
name|enableAdvisoryForConsumed
parameter_list|()
block|{
name|getDefaultPolicyEntry
argument_list|()
operator|.
name|setAdvisoryForConsumed
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|disableAdvisoryForConsumed
parameter_list|()
block|{
name|getDefaultPolicyEntry
argument_list|()
operator|.
name|setAdvisoryForConsumed
argument_list|(
literal|false
argument_list|)
expr_stmt|;
block|}
specifier|public
name|boolean
name|isAdvisoryForDiscardingMessagesEnabled
parameter_list|()
block|{
return|return
name|getDefaultPolicyEntry
argument_list|()
operator|.
name|isAdvisoryForDiscardingMessages
argument_list|()
return|;
block|}
specifier|public
name|void
name|enableAdvisoryForDiscardingMessages
parameter_list|()
block|{
name|getDefaultPolicyEntry
argument_list|()
operator|.
name|setAdvisoryForDiscardingMessages
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|disableAdvisoryForDiscardingMessages
parameter_list|()
block|{
name|getDefaultPolicyEntry
argument_list|()
operator|.
name|setAdvisoryForDiscardingMessages
argument_list|(
literal|false
argument_list|)
expr_stmt|;
block|}
specifier|public
name|boolean
name|isAdvisoryForFastProducersEnabled
parameter_list|()
block|{
return|return
name|getDefaultPolicyEntry
argument_list|()
operator|.
name|isAdvisoryForFastProducers
argument_list|()
return|;
block|}
specifier|public
name|void
name|enableAdvisoryForFastProducers
parameter_list|()
block|{
name|getDefaultPolicyEntry
argument_list|()
operator|.
name|setAdvisoryForFastProducers
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|disableAdvisoryForFastProducers
parameter_list|()
block|{
name|getDefaultPolicyEntry
argument_list|()
operator|.
name|setAdvisoryForFastProducers
argument_list|(
literal|false
argument_list|)
expr_stmt|;
block|}
specifier|public
name|boolean
name|isAdvisoryForSlowConsumersEnabled
parameter_list|()
block|{
return|return
name|getDefaultPolicyEntry
argument_list|()
operator|.
name|isAdvisoryForSlowConsumers
argument_list|()
return|;
block|}
specifier|public
name|void
name|enableAdvisoryForSlowConsumers
parameter_list|()
block|{
name|getDefaultPolicyEntry
argument_list|()
operator|.
name|setAdvisoryForSlowConsumers
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|disableAdvisoryForSlowConsumers
parameter_list|()
block|{
name|getDefaultPolicyEntry
argument_list|()
operator|.
name|setAdvisoryForSlowConsumers
argument_list|(
literal|false
argument_list|)
expr_stmt|;
block|}
comment|/**      * Get the number of messages in a specific JMS Destination.      *<p/>      * The full name of the JMS destination including the prefix should be provided - i.e. queue://myQueue      * or topic://myTopic.  If the destination type prefix is not included in the destination name, a prefix      * of "queue://" is assumed.      *      * @param destinationName the full name of the JMS Destination      * @return the number of messages in the JMS Destination      */
specifier|public
name|long
name|getMessageCount
parameter_list|(
name|String
name|destinationName
parameter_list|)
block|{
if|if
condition|(
literal|null
operator|==
name|brokerService
condition|)
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
literal|"BrokerService has not yet been created - was before() called?"
argument_list|)
throw|;
block|}
comment|// TODO: Figure out how to do this for Topics
name|Destination
name|destination
init|=
name|getDestination
argument_list|(
name|destinationName
argument_list|)
decl_stmt|;
if|if
condition|(
name|destination
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"Failed to find destination: "
operator|+
name|destinationName
argument_list|)
throw|;
block|}
comment|// return destination.getMessageStore().getMessageCount();
return|return
name|destination
operator|.
name|getDestinationStatistics
argument_list|()
operator|.
name|getMessages
argument_list|()
operator|.
name|getCount
argument_list|()
return|;
block|}
comment|/**      * Get the ActiveMQ destination      *<p/>      * The full name of the JMS destination including the prefix should be provided - i.e. queue://myQueue      * or topic://myTopic.  If the destination type prefix is not included in the destination name, a prefix      * of "queue://" is assumed.      *      * @param destinationName the full name of the JMS Destination      * @return the ActiveMQ destination, null if not found      */
specifier|public
name|Destination
name|getDestination
parameter_list|(
name|String
name|destinationName
parameter_list|)
block|{
if|if
condition|(
literal|null
operator|==
name|brokerService
condition|)
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
literal|"BrokerService has not yet been created - was before() called?"
argument_list|)
throw|;
block|}
name|Destination
name|destination
init|=
literal|null
decl_stmt|;
try|try
block|{
name|destination
operator|=
name|brokerService
operator|.
name|getDestination
argument_list|(
name|ActiveMQDestination
operator|.
name|createDestination
argument_list|(
name|destinationName
argument_list|,
name|QUEUE_TYPE
argument_list|)
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|RuntimeException
name|runtimeEx
parameter_list|)
block|{
throw|throw
name|runtimeEx
throw|;
block|}
catch|catch
parameter_list|(
name|Exception
name|ex
parameter_list|)
block|{
throw|throw
operator|new
name|EmbeddedActiveMQBrokerException
argument_list|(
literal|"Unexpected exception getting destination from broker"
argument_list|,
name|ex
argument_list|)
throw|;
block|}
return|return
name|destination
return|;
block|}
specifier|private
name|PolicyEntry
name|getDefaultPolicyEntry
parameter_list|()
block|{
name|PolicyMap
name|destinationPolicy
init|=
name|brokerService
operator|.
name|getDestinationPolicy
argument_list|()
decl_stmt|;
if|if
condition|(
literal|null
operator|==
name|destinationPolicy
condition|)
block|{
name|destinationPolicy
operator|=
operator|new
name|PolicyMap
argument_list|()
expr_stmt|;
name|brokerService
operator|.
name|setDestinationPolicy
argument_list|(
name|destinationPolicy
argument_list|)
expr_stmt|;
block|}
name|PolicyEntry
name|defaultEntry
init|=
name|destinationPolicy
operator|.
name|getDefaultEntry
argument_list|()
decl_stmt|;
if|if
condition|(
literal|null
operator|==
name|defaultEntry
condition|)
block|{
name|defaultEntry
operator|=
operator|new
name|PolicyEntry
argument_list|()
expr_stmt|;
name|destinationPolicy
operator|.
name|setDefaultEntry
argument_list|(
name|defaultEntry
argument_list|)
expr_stmt|;
block|}
return|return
name|defaultEntry
return|;
block|}
specifier|public
name|BytesMessage
name|createBytesMessage
parameter_list|()
block|{
return|return
name|internalClient
operator|.
name|createBytesMessage
argument_list|()
return|;
block|}
specifier|public
name|TextMessage
name|createTextMessage
parameter_list|()
block|{
return|return
name|internalClient
operator|.
name|createTextMessage
argument_list|()
return|;
block|}
specifier|public
name|MapMessage
name|createMapMessage
parameter_list|()
block|{
return|return
name|internalClient
operator|.
name|createMapMessage
argument_list|()
return|;
block|}
specifier|public
name|ObjectMessage
name|createObjectMessage
parameter_list|()
block|{
return|return
name|internalClient
operator|.
name|createObjectMessage
argument_list|()
return|;
block|}
specifier|public
name|StreamMessage
name|createStreamMessage
parameter_list|()
block|{
return|return
name|internalClient
operator|.
name|createStreamMessage
argument_list|()
return|;
block|}
specifier|public
name|BytesMessage
name|createMessage
parameter_list|(
name|byte
index|[]
name|body
parameter_list|)
block|{
return|return
name|this
operator|.
name|createMessage
argument_list|(
name|body
argument_list|,
literal|null
argument_list|)
return|;
block|}
specifier|public
name|TextMessage
name|createMessage
parameter_list|(
name|String
name|body
parameter_list|)
block|{
return|return
name|this
operator|.
name|createMessage
argument_list|(
name|body
argument_list|,
literal|null
argument_list|)
return|;
block|}
specifier|public
name|MapMessage
name|createMessage
parameter_list|(
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|body
parameter_list|)
block|{
return|return
name|this
operator|.
name|createMessage
argument_list|(
name|body
argument_list|,
literal|null
argument_list|)
return|;
block|}
specifier|public
name|ObjectMessage
name|createMessage
parameter_list|(
name|Serializable
name|body
parameter_list|)
block|{
return|return
name|this
operator|.
name|createMessage
argument_list|(
name|body
argument_list|,
literal|null
argument_list|)
return|;
block|}
specifier|public
name|BytesMessage
name|createMessage
parameter_list|(
name|byte
index|[]
name|body
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|properties
parameter_list|)
block|{
name|BytesMessage
name|message
init|=
name|this
operator|.
name|createBytesMessage
argument_list|()
decl_stmt|;
if|if
condition|(
name|body
operator|!=
literal|null
condition|)
block|{
try|try
block|{
name|message
operator|.
name|writeBytes
argument_list|(
name|body
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|JMSException
name|jmsEx
parameter_list|)
block|{
throw|throw
operator|new
name|EmbeddedActiveMQBrokerException
argument_list|(
name|String
operator|.
name|format
argument_list|(
literal|"Failed to set body {%s} on BytesMessage"
argument_list|,
operator|new
name|String
argument_list|(
name|body
argument_list|)
argument_list|)
argument_list|,
name|jmsEx
argument_list|)
throw|;
block|}
block|}
name|setMessageProperties
argument_list|(
name|message
argument_list|,
name|properties
argument_list|)
expr_stmt|;
return|return
name|message
return|;
block|}
specifier|public
name|TextMessage
name|createMessage
parameter_list|(
name|String
name|body
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|properties
parameter_list|)
block|{
name|TextMessage
name|message
init|=
name|this
operator|.
name|createTextMessage
argument_list|()
decl_stmt|;
if|if
condition|(
name|body
operator|!=
literal|null
condition|)
block|{
try|try
block|{
name|message
operator|.
name|setText
argument_list|(
name|body
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|JMSException
name|jmsEx
parameter_list|)
block|{
throw|throw
operator|new
name|EmbeddedActiveMQBrokerException
argument_list|(
name|String
operator|.
name|format
argument_list|(
literal|"Failed to set body {%s} on TextMessage"
argument_list|,
name|body
argument_list|)
argument_list|,
name|jmsEx
argument_list|)
throw|;
block|}
block|}
name|setMessageProperties
argument_list|(
name|message
argument_list|,
name|properties
argument_list|)
expr_stmt|;
return|return
name|message
return|;
block|}
specifier|public
name|MapMessage
name|createMessage
parameter_list|(
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|body
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|properties
parameter_list|)
block|{
name|MapMessage
name|message
init|=
name|this
operator|.
name|createMapMessage
argument_list|()
decl_stmt|;
if|if
condition|(
name|body
operator|!=
literal|null
condition|)
block|{
for|for
control|(
name|Map
operator|.
name|Entry
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|entry
range|:
name|body
operator|.
name|entrySet
argument_list|()
control|)
block|{
try|try
block|{
name|message
operator|.
name|setObject
argument_list|(
name|entry
operator|.
name|getKey
argument_list|()
argument_list|,
name|entry
operator|.
name|getValue
argument_list|()
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|JMSException
name|jmsEx
parameter_list|)
block|{
throw|throw
operator|new
name|EmbeddedActiveMQBrokerException
argument_list|(
name|String
operator|.
name|format
argument_list|(
literal|"Failed to set body entry {%s = %s} on MapMessage"
argument_list|,
name|entry
operator|.
name|getKey
argument_list|()
argument_list|,
name|entry
operator|.
name|getValue
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
argument_list|,
name|jmsEx
argument_list|)
throw|;
block|}
block|}
block|}
name|setMessageProperties
argument_list|(
name|message
argument_list|,
name|properties
argument_list|)
expr_stmt|;
return|return
name|message
return|;
block|}
specifier|public
name|ObjectMessage
name|createMessage
parameter_list|(
name|Serializable
name|body
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|properties
parameter_list|)
block|{
name|ObjectMessage
name|message
init|=
name|this
operator|.
name|createObjectMessage
argument_list|()
decl_stmt|;
if|if
condition|(
name|body
operator|!=
literal|null
condition|)
block|{
try|try
block|{
name|message
operator|.
name|setObject
argument_list|(
name|body
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|JMSException
name|jmsEx
parameter_list|)
block|{
throw|throw
operator|new
name|EmbeddedActiveMQBrokerException
argument_list|(
name|String
operator|.
name|format
argument_list|(
literal|"Failed to set body {%s} on ObjectMessage"
argument_list|,
name|body
operator|.
name|toString
argument_list|()
argument_list|)
argument_list|,
name|jmsEx
argument_list|)
throw|;
block|}
block|}
name|setMessageProperties
argument_list|(
name|message
argument_list|,
name|properties
argument_list|)
expr_stmt|;
return|return
name|message
return|;
block|}
specifier|public
name|void
name|pushMessage
parameter_list|(
name|String
name|destinationName
parameter_list|,
name|Message
name|message
parameter_list|)
block|{
if|if
condition|(
name|destinationName
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"pushMessage failure - destination name is required"
argument_list|)
throw|;
block|}
elseif|else
if|if
condition|(
name|message
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"pushMessage failure - a Message is required"
argument_list|)
throw|;
block|}
name|ActiveMQDestination
name|destination
init|=
name|ActiveMQDestination
operator|.
name|createDestination
argument_list|(
name|destinationName
argument_list|,
name|ActiveMQDestination
operator|.
name|QUEUE_TYPE
argument_list|)
decl_stmt|;
name|internalClient
operator|.
name|pushMessage
argument_list|(
name|destination
argument_list|,
name|message
argument_list|)
expr_stmt|;
block|}
specifier|public
name|BytesMessage
name|pushMessage
parameter_list|(
name|String
name|destinationName
parameter_list|,
name|byte
index|[]
name|body
parameter_list|)
block|{
name|BytesMessage
name|message
init|=
name|createMessage
argument_list|(
name|body
argument_list|,
literal|null
argument_list|)
decl_stmt|;
name|pushMessage
argument_list|(
name|destinationName
argument_list|,
name|message
argument_list|)
expr_stmt|;
return|return
name|message
return|;
block|}
specifier|public
name|TextMessage
name|pushMessage
parameter_list|(
name|String
name|destinationName
parameter_list|,
name|String
name|body
parameter_list|)
block|{
name|TextMessage
name|message
init|=
name|createMessage
argument_list|(
name|body
argument_list|,
literal|null
argument_list|)
decl_stmt|;
name|pushMessage
argument_list|(
name|destinationName
argument_list|,
name|message
argument_list|)
expr_stmt|;
return|return
name|message
return|;
block|}
specifier|public
name|MapMessage
name|pushMessage
parameter_list|(
name|String
name|destinationName
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|body
parameter_list|)
block|{
name|MapMessage
name|message
init|=
name|createMessage
argument_list|(
name|body
argument_list|,
literal|null
argument_list|)
decl_stmt|;
name|pushMessage
argument_list|(
name|destinationName
argument_list|,
name|message
argument_list|)
expr_stmt|;
return|return
name|message
return|;
block|}
specifier|public
name|ObjectMessage
name|pushMessage
parameter_list|(
name|String
name|destinationName
parameter_list|,
name|Serializable
name|body
parameter_list|)
block|{
name|ObjectMessage
name|message
init|=
name|createMessage
argument_list|(
name|body
argument_list|,
literal|null
argument_list|)
decl_stmt|;
name|pushMessage
argument_list|(
name|destinationName
argument_list|,
name|message
argument_list|)
expr_stmt|;
return|return
name|message
return|;
block|}
specifier|public
name|BytesMessage
name|pushMessageWithProperties
parameter_list|(
name|String
name|destinationName
parameter_list|,
name|byte
index|[]
name|body
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|properties
parameter_list|)
block|{
name|BytesMessage
name|message
init|=
name|createMessage
argument_list|(
name|body
argument_list|,
name|properties
argument_list|)
decl_stmt|;
name|pushMessage
argument_list|(
name|destinationName
argument_list|,
name|message
argument_list|)
expr_stmt|;
return|return
name|message
return|;
block|}
specifier|public
name|TextMessage
name|pushMessageWithProperties
parameter_list|(
name|String
name|destinationName
parameter_list|,
name|String
name|body
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|properties
parameter_list|)
block|{
name|TextMessage
name|message
init|=
name|createMessage
argument_list|(
name|body
argument_list|,
name|properties
argument_list|)
decl_stmt|;
name|pushMessage
argument_list|(
name|destinationName
argument_list|,
name|message
argument_list|)
expr_stmt|;
return|return
name|message
return|;
block|}
specifier|public
name|MapMessage
name|pushMessageWithProperties
parameter_list|(
name|String
name|destinationName
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|body
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|properties
parameter_list|)
block|{
name|MapMessage
name|message
init|=
name|createMessage
argument_list|(
name|body
argument_list|,
name|properties
argument_list|)
decl_stmt|;
name|pushMessage
argument_list|(
name|destinationName
argument_list|,
name|message
argument_list|)
expr_stmt|;
return|return
name|message
return|;
block|}
specifier|public
name|ObjectMessage
name|pushMessageWithProperties
parameter_list|(
name|String
name|destinationName
parameter_list|,
name|Serializable
name|body
parameter_list|,
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|properties
parameter_list|)
block|{
name|ObjectMessage
name|message
init|=
name|createMessage
argument_list|(
name|body
argument_list|,
name|properties
argument_list|)
decl_stmt|;
name|pushMessage
argument_list|(
name|destinationName
argument_list|,
name|message
argument_list|)
expr_stmt|;
return|return
name|message
return|;
block|}
specifier|public
name|Message
name|peekMessage
parameter_list|(
name|String
name|destinationName
parameter_list|)
block|{
if|if
condition|(
literal|null
operator|==
name|brokerService
condition|)
block|{
throw|throw
operator|new
name|NullPointerException
argument_list|(
literal|"peekMessage failure  - BrokerService is null"
argument_list|)
throw|;
block|}
if|if
condition|(
name|destinationName
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|IllegalArgumentException
argument_list|(
literal|"peekMessage failure - destination name is required"
argument_list|)
throw|;
block|}
name|ActiveMQDestination
name|destination
init|=
name|ActiveMQDestination
operator|.
name|createDestination
argument_list|(
name|destinationName
argument_list|,
name|ActiveMQDestination
operator|.
name|QUEUE_TYPE
argument_list|)
decl_stmt|;
name|Destination
name|brokerDestination
init|=
literal|null
decl_stmt|;
try|try
block|{
name|brokerDestination
operator|=
name|brokerService
operator|.
name|getDestination
argument_list|(
name|destination
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Exception
name|ex
parameter_list|)
block|{
throw|throw
operator|new
name|EmbeddedActiveMQBrokerException
argument_list|(
literal|"peekMessage failure - unexpected exception getting destination from BrokerService"
argument_list|,
name|ex
argument_list|)
throw|;
block|}
if|if
condition|(
name|brokerDestination
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
name|String
operator|.
name|format
argument_list|(
literal|"peekMessage failure - destination %s not found in broker %s"
argument_list|,
name|destination
operator|.
name|toString
argument_list|()
argument_list|,
name|brokerService
operator|.
name|getBrokerName
argument_list|()
argument_list|)
argument_list|)
throw|;
block|}
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|command
operator|.
name|Message
index|[]
name|messages
init|=
name|brokerDestination
operator|.
name|browse
argument_list|()
decl_stmt|;
if|if
condition|(
name|messages
operator|!=
literal|null
operator|&&
name|messages
operator|.
name|length
operator|>
literal|0
condition|)
block|{
return|return
operator|(
name|Message
operator|)
name|messages
index|[
literal|0
index|]
return|;
block|}
return|return
literal|null
return|;
block|}
specifier|public
name|BytesMessage
name|peekBytesMessage
parameter_list|(
name|String
name|destinationName
parameter_list|)
block|{
return|return
operator|(
name|BytesMessage
operator|)
name|peekMessage
argument_list|(
name|destinationName
argument_list|)
return|;
block|}
specifier|public
name|TextMessage
name|peekTextMessage
parameter_list|(
name|String
name|destinationName
parameter_list|)
block|{
return|return
operator|(
name|TextMessage
operator|)
name|peekMessage
argument_list|(
name|destinationName
argument_list|)
return|;
block|}
specifier|public
name|MapMessage
name|peekMapMessage
parameter_list|(
name|String
name|destinationName
parameter_list|)
block|{
return|return
operator|(
name|MapMessage
operator|)
name|peekMessage
argument_list|(
name|destinationName
argument_list|)
return|;
block|}
specifier|public
name|ObjectMessage
name|peekObjectMessage
parameter_list|(
name|String
name|destinationName
parameter_list|)
block|{
return|return
operator|(
name|ObjectMessage
operator|)
name|peekMessage
argument_list|(
name|destinationName
argument_list|)
return|;
block|}
specifier|public
name|StreamMessage
name|peekStreamMessage
parameter_list|(
name|String
name|destinationName
parameter_list|)
block|{
return|return
operator|(
name|StreamMessage
operator|)
name|peekMessage
argument_list|(
name|destinationName
argument_list|)
return|;
block|}
specifier|public
specifier|static
class|class
name|EmbeddedActiveMQBrokerException
extends|extends
name|RuntimeException
block|{
specifier|public
name|EmbeddedActiveMQBrokerException
parameter_list|(
name|String
name|message
parameter_list|)
block|{
name|super
argument_list|(
name|message
argument_list|)
expr_stmt|;
block|}
specifier|public
name|EmbeddedActiveMQBrokerException
parameter_list|(
name|String
name|message
parameter_list|,
name|Exception
name|cause
parameter_list|)
block|{
name|super
argument_list|(
name|message
argument_list|,
name|cause
argument_list|)
expr_stmt|;
block|}
block|}
specifier|private
class|class
name|InternalClient
block|{
name|ActiveMQConnectionFactory
name|connectionFactory
decl_stmt|;
name|Connection
name|connection
decl_stmt|;
name|Session
name|session
decl_stmt|;
name|MessageProducer
name|producer
decl_stmt|;
specifier|public
name|InternalClient
parameter_list|()
block|{         }
name|void
name|start
parameter_list|()
block|{
name|connectionFactory
operator|=
name|createConnectionFactory
argument_list|()
expr_stmt|;
try|try
block|{
name|connection
operator|=
name|connectionFactory
operator|.
name|createConnection
argument_list|()
expr_stmt|;
name|session
operator|=
name|connection
operator|.
name|createSession
argument_list|(
literal|false
argument_list|,
name|Session
operator|.
name|AUTO_ACKNOWLEDGE
argument_list|)
expr_stmt|;
name|producer
operator|=
name|session
operator|.
name|createProducer
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|connection
operator|.
name|start
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|JMSException
name|jmsEx
parameter_list|)
block|{
throw|throw
operator|new
name|EmbeddedActiveMQBrokerException
argument_list|(
literal|"Internal Client creation failure"
argument_list|,
name|jmsEx
argument_list|)
throw|;
block|}
block|}
name|void
name|stop
parameter_list|()
block|{
if|if
condition|(
literal|null
operator|!=
name|connection
condition|)
block|{
try|try
block|{
name|connection
operator|.
name|close
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|JMSException
name|jmsEx
parameter_list|)
block|{
name|log
operator|.
name|warn
argument_list|(
literal|"JMSException encounter closing InternalClient connection - ignoring"
argument_list|,
name|jmsEx
argument_list|)
expr_stmt|;
block|}
block|}
block|}
specifier|public
name|BytesMessage
name|createBytesMessage
parameter_list|()
block|{
name|checkSession
argument_list|()
expr_stmt|;
try|try
block|{
return|return
name|session
operator|.
name|createBytesMessage
argument_list|()
return|;
block|}
catch|catch
parameter_list|(
name|JMSException
name|jmsEx
parameter_list|)
block|{
throw|throw
operator|new
name|EmbeddedActiveMQBrokerException
argument_list|(
literal|"Failed to create BytesMessage"
argument_list|,
name|jmsEx
argument_list|)
throw|;
block|}
block|}
specifier|public
name|TextMessage
name|createTextMessage
parameter_list|()
block|{
name|checkSession
argument_list|()
expr_stmt|;
try|try
block|{
return|return
name|session
operator|.
name|createTextMessage
argument_list|()
return|;
block|}
catch|catch
parameter_list|(
name|JMSException
name|jmsEx
parameter_list|)
block|{
throw|throw
operator|new
name|EmbeddedActiveMQBrokerException
argument_list|(
literal|"Failed to create TextMessage"
argument_list|,
name|jmsEx
argument_list|)
throw|;
block|}
block|}
specifier|public
name|MapMessage
name|createMapMessage
parameter_list|()
block|{
name|checkSession
argument_list|()
expr_stmt|;
try|try
block|{
return|return
name|session
operator|.
name|createMapMessage
argument_list|()
return|;
block|}
catch|catch
parameter_list|(
name|JMSException
name|jmsEx
parameter_list|)
block|{
throw|throw
operator|new
name|EmbeddedActiveMQBrokerException
argument_list|(
literal|"Failed to create MapMessage"
argument_list|,
name|jmsEx
argument_list|)
throw|;
block|}
block|}
specifier|public
name|ObjectMessage
name|createObjectMessage
parameter_list|()
block|{
name|checkSession
argument_list|()
expr_stmt|;
try|try
block|{
return|return
name|session
operator|.
name|createObjectMessage
argument_list|()
return|;
block|}
catch|catch
parameter_list|(
name|JMSException
name|jmsEx
parameter_list|)
block|{
throw|throw
operator|new
name|EmbeddedActiveMQBrokerException
argument_list|(
literal|"Failed to create ObjectMessage"
argument_list|,
name|jmsEx
argument_list|)
throw|;
block|}
block|}
specifier|public
name|StreamMessage
name|createStreamMessage
parameter_list|()
block|{
name|checkSession
argument_list|()
expr_stmt|;
try|try
block|{
return|return
name|session
operator|.
name|createStreamMessage
argument_list|()
return|;
block|}
catch|catch
parameter_list|(
name|JMSException
name|jmsEx
parameter_list|)
block|{
throw|throw
operator|new
name|EmbeddedActiveMQBrokerException
argument_list|(
literal|"Failed to create StreamMessage"
argument_list|,
name|jmsEx
argument_list|)
throw|;
block|}
block|}
specifier|public
name|void
name|pushMessage
parameter_list|(
name|ActiveMQDestination
name|destination
parameter_list|,
name|Message
name|message
parameter_list|)
block|{
if|if
condition|(
name|producer
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
literal|"JMS MessageProducer is null - has the InternalClient been started?"
argument_list|)
throw|;
block|}
try|try
block|{
name|producer
operator|.
name|send
argument_list|(
name|destination
argument_list|,
name|message
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|JMSException
name|jmsEx
parameter_list|)
block|{
throw|throw
operator|new
name|EmbeddedActiveMQBrokerException
argument_list|(
name|String
operator|.
name|format
argument_list|(
literal|"Failed to push %s to %s"
argument_list|,
name|message
operator|.
name|getClass
argument_list|()
operator|.
name|getSimpleName
argument_list|()
argument_list|,
name|destination
operator|.
name|toString
argument_list|()
argument_list|)
argument_list|,
name|jmsEx
argument_list|)
throw|;
block|}
block|}
name|void
name|checkSession
parameter_list|()
block|{
if|if
condition|(
name|session
operator|==
literal|null
condition|)
block|{
throw|throw
operator|new
name|IllegalStateException
argument_list|(
literal|"JMS Session is null - has the InternalClient been started?"
argument_list|)
throw|;
block|}
block|}
block|}
block|}
end_class

end_unit

