begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_package
package|package
name|org
operator|.
name|activeio
operator|.
name|oneport
operator|.
name|openorb
package|;
end_package

begin_comment
comment|/**  * Holder class for : TestIIOPServer  *   * @author OpenORB Compiler  */
end_comment

begin_class
specifier|final
specifier|public
class|class
name|TestIIOPServerHolder
implements|implements
name|org
operator|.
name|omg
operator|.
name|CORBA
operator|.
name|portable
operator|.
name|Streamable
block|{
comment|/**      * Internal TestIIOPServer value      */
specifier|public
name|org
operator|.
name|activeio
operator|.
name|oneport
operator|.
name|openorb
operator|.
name|TestIIOPServer
name|value
decl_stmt|;
comment|/**      * Default constructor      */
specifier|public
name|TestIIOPServerHolder
parameter_list|()
block|{ }
comment|/**      * Constructor with value initialisation      * @param initial the initial value      */
specifier|public
name|TestIIOPServerHolder
parameter_list|(
name|org
operator|.
name|activeio
operator|.
name|oneport
operator|.
name|openorb
operator|.
name|TestIIOPServer
name|initial
parameter_list|)
block|{
name|value
operator|=
name|initial
expr_stmt|;
block|}
comment|/**      * Read TestIIOPServer from a marshalled stream      * @param istream the input stream      */
specifier|public
name|void
name|_read
parameter_list|(
name|org
operator|.
name|omg
operator|.
name|CORBA
operator|.
name|portable
operator|.
name|InputStream
name|istream
parameter_list|)
block|{
name|value
operator|=
name|TestIIOPServerHelper
operator|.
name|read
argument_list|(
name|istream
argument_list|)
expr_stmt|;
block|}
comment|/**      * Write TestIIOPServer into a marshalled stream      * @param ostream the output stream      */
specifier|public
name|void
name|_write
parameter_list|(
name|org
operator|.
name|omg
operator|.
name|CORBA
operator|.
name|portable
operator|.
name|OutputStream
name|ostream
parameter_list|)
block|{
name|TestIIOPServerHelper
operator|.
name|write
argument_list|(
name|ostream
argument_list|,
name|value
argument_list|)
expr_stmt|;
block|}
comment|/**      * Return the TestIIOPServer TypeCode      * @return a TypeCode      */
specifier|public
name|org
operator|.
name|omg
operator|.
name|CORBA
operator|.
name|TypeCode
name|_type
parameter_list|()
block|{
return|return
name|TestIIOPServerHelper
operator|.
name|type
argument_list|()
return|;
block|}
block|}
end_class

end_unit

