begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|command
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|JMSException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|MessageNotReadableException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|MessageNotWriteableException
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestCase
import|;
end_import

begin_comment
comment|/**  * @version $Revision$  */
end_comment

begin_class
specifier|public
class|class
name|ActiveMQObjectMessageTest
extends|extends
name|TestCase
block|{
comment|/**      * Constructor for ActiveMQObjectMessageTest.      *      * @param name      */
specifier|public
name|ActiveMQObjectMessageTest
parameter_list|(
name|String
name|name
parameter_list|)
block|{
name|super
argument_list|(
name|name
argument_list|)
expr_stmt|;
block|}
specifier|public
specifier|static
name|void
name|main
parameter_list|(
name|String
index|[]
name|args
parameter_list|)
block|{
name|junit
operator|.
name|textui
operator|.
name|TestRunner
operator|.
name|run
argument_list|(
name|ActiveMQObjectMessageTest
operator|.
name|class
argument_list|)
expr_stmt|;
block|}
comment|/*      * @see TestCase#setUp()      */
specifier|protected
name|void
name|setUp
parameter_list|()
throws|throws
name|Exception
block|{
name|super
operator|.
name|setUp
argument_list|()
expr_stmt|;
block|}
comment|/*      * @see TestCase#tearDown()      */
specifier|protected
name|void
name|tearDown
parameter_list|()
throws|throws
name|Exception
block|{
name|super
operator|.
name|tearDown
argument_list|()
expr_stmt|;
block|}
specifier|public
name|void
name|testBytes
parameter_list|()
throws|throws
name|JMSException
throws|,
name|IOException
block|{
name|ActiveMQObjectMessage
name|msg
init|=
operator|new
name|ActiveMQObjectMessage
argument_list|()
decl_stmt|;
name|String
name|str
init|=
literal|"testText"
decl_stmt|;
name|msg
operator|.
name|setObject
argument_list|(
name|str
argument_list|)
expr_stmt|;
name|msg
operator|=
operator|(
name|ActiveMQObjectMessage
operator|)
name|msg
operator|.
name|copy
argument_list|()
expr_stmt|;
name|assertEquals
argument_list|(
name|msg
operator|.
name|getObject
argument_list|()
argument_list|,
name|str
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testSetObject
parameter_list|()
throws|throws
name|JMSException
block|{
name|ActiveMQObjectMessage
name|msg
init|=
operator|new
name|ActiveMQObjectMessage
argument_list|()
decl_stmt|;
name|String
name|str
init|=
literal|"testText"
decl_stmt|;
name|msg
operator|.
name|setObject
argument_list|(
name|str
argument_list|)
expr_stmt|;
name|assertTrue
argument_list|(
name|msg
operator|.
name|getObject
argument_list|()
operator|==
name|str
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testClearBody
parameter_list|()
throws|throws
name|JMSException
block|{
name|ActiveMQObjectMessage
name|objectMessage
init|=
operator|new
name|ActiveMQObjectMessage
argument_list|()
decl_stmt|;
try|try
block|{
name|objectMessage
operator|.
name|setObject
argument_list|(
literal|"String"
argument_list|)
expr_stmt|;
name|objectMessage
operator|.
name|clearBody
argument_list|()
expr_stmt|;
name|assertFalse
argument_list|(
name|objectMessage
operator|.
name|isReadOnlyBody
argument_list|()
argument_list|)
expr_stmt|;
name|assertNull
argument_list|(
name|objectMessage
operator|.
name|getObject
argument_list|()
argument_list|)
expr_stmt|;
name|objectMessage
operator|.
name|setObject
argument_list|(
literal|"String"
argument_list|)
expr_stmt|;
name|objectMessage
operator|.
name|getObject
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|MessageNotWriteableException
name|mnwe
parameter_list|)
block|{
name|fail
argument_list|(
literal|"should be writeable"
argument_list|)
expr_stmt|;
block|}
block|}
specifier|public
name|void
name|testReadOnlyBody
parameter_list|()
throws|throws
name|JMSException
block|{
name|ActiveMQObjectMessage
name|msg
init|=
operator|new
name|ActiveMQObjectMessage
argument_list|()
decl_stmt|;
name|msg
operator|.
name|setObject
argument_list|(
literal|"test"
argument_list|)
expr_stmt|;
name|msg
operator|.
name|setReadOnlyBody
argument_list|(
literal|true
argument_list|)
expr_stmt|;
try|try
block|{
name|msg
operator|.
name|getObject
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|MessageNotReadableException
name|e
parameter_list|)
block|{
name|fail
argument_list|(
literal|"should be readable"
argument_list|)
expr_stmt|;
block|}
try|try
block|{
name|msg
operator|.
name|setObject
argument_list|(
literal|"test"
argument_list|)
expr_stmt|;
name|fail
argument_list|(
literal|"should throw exception"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|MessageNotWriteableException
name|e
parameter_list|)
block|{         }
block|}
specifier|public
name|void
name|testWriteOnlyBody
parameter_list|()
throws|throws
name|JMSException
block|{
comment|// should always be readable
name|ActiveMQObjectMessage
name|msg
init|=
operator|new
name|ActiveMQObjectMessage
argument_list|()
decl_stmt|;
name|msg
operator|.
name|setReadOnlyBody
argument_list|(
literal|false
argument_list|)
expr_stmt|;
try|try
block|{
name|msg
operator|.
name|setObject
argument_list|(
literal|"test"
argument_list|)
expr_stmt|;
name|msg
operator|.
name|getObject
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|MessageNotReadableException
name|e
parameter_list|)
block|{
name|fail
argument_list|(
literal|"should be readable"
argument_list|)
expr_stmt|;
block|}
name|msg
operator|.
name|setReadOnlyBody
argument_list|(
literal|true
argument_list|)
expr_stmt|;
try|try
block|{
name|msg
operator|.
name|getObject
argument_list|()
expr_stmt|;
name|msg
operator|.
name|setObject
argument_list|(
literal|"test"
argument_list|)
expr_stmt|;
name|fail
argument_list|(
literal|"should throw exception"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|MessageNotReadableException
name|e
parameter_list|)
block|{
name|fail
argument_list|(
literal|"should be readable"
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|MessageNotWriteableException
name|mnwe
parameter_list|)
block|{         }
block|}
block|}
end_class

end_unit

