begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|store
operator|.
name|kahadb
package|;
end_package

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertEquals
import|;
end_import

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertTrue
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|URI
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collection
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|jms
operator|.
name|JMSException
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|broker
operator|.
name|Broker
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|broker
operator|.
name|BrokerService
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|broker
operator|.
name|TransportConnector
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|command
operator|.
name|ActiveMQDestination
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|io
operator|.
name|FileUtils
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|commons
operator|.
name|io
operator|.
name|filefilter
operator|.
name|WildcardFileFilter
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|After
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Before
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Rule
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|rules
operator|.
name|TemporaryFolder
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|Logger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|LoggerFactory
import|;
end_import

begin_class
specifier|public
specifier|abstract
class|class
name|AbstractMultiKahaDBDeletionTest
block|{
specifier|protected
specifier|static
specifier|final
name|Logger
name|LOG
init|=
name|LoggerFactory
operator|.
name|getLogger
argument_list|(
name|MultiKahaDBTopicDeletionTest
operator|.
name|class
argument_list|)
decl_stmt|;
specifier|protected
name|BrokerService
name|brokerService
decl_stmt|;
specifier|protected
name|Broker
name|broker
decl_stmt|;
specifier|protected
name|URI
name|brokerConnectURI
decl_stmt|;
specifier|protected
name|File
name|storeDir
decl_stmt|;
specifier|protected
name|ActiveMQDestination
name|dest1
decl_stmt|;
specifier|protected
name|ActiveMQDestination
name|dest2
decl_stmt|;
specifier|public
name|AbstractMultiKahaDBDeletionTest
parameter_list|(
name|ActiveMQDestination
name|dest1
parameter_list|,
name|ActiveMQDestination
name|dest2
parameter_list|)
block|{
name|this
operator|.
name|dest1
operator|=
name|dest1
expr_stmt|;
name|this
operator|.
name|dest2
operator|=
name|dest2
expr_stmt|;
block|}
annotation|@
name|Rule
specifier|public
name|TemporaryFolder
name|tempTestDir
init|=
operator|new
name|TemporaryFolder
argument_list|()
decl_stmt|;
annotation|@
name|Before
specifier|public
name|void
name|startBroker
parameter_list|()
throws|throws
name|Exception
block|{
name|setUpBroker
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
specifier|protected
name|void
name|setUpBroker
parameter_list|(
name|boolean
name|clearDataDir
parameter_list|)
throws|throws
name|Exception
block|{
name|brokerService
operator|=
operator|new
name|BrokerService
argument_list|()
expr_stmt|;
name|this
operator|.
name|initPersistence
argument_list|(
name|brokerService
argument_list|)
expr_stmt|;
comment|// set up a transport
name|TransportConnector
name|connector
init|=
name|brokerService
operator|.
name|addConnector
argument_list|(
operator|new
name|TransportConnector
argument_list|()
argument_list|)
decl_stmt|;
name|connector
operator|.
name|setUri
argument_list|(
operator|new
name|URI
argument_list|(
literal|"tcp://0.0.0.0:0"
argument_list|)
argument_list|)
expr_stmt|;
name|connector
operator|.
name|setName
argument_list|(
literal|"tcp"
argument_list|)
expr_stmt|;
name|brokerService
operator|.
name|start
argument_list|()
expr_stmt|;
name|brokerService
operator|.
name|waitUntilStarted
argument_list|()
expr_stmt|;
name|brokerConnectURI
operator|=
name|brokerService
operator|.
name|getConnectorByName
argument_list|(
literal|"tcp"
argument_list|)
operator|.
name|getConnectUri
argument_list|()
expr_stmt|;
name|broker
operator|=
name|brokerService
operator|.
name|getBroker
argument_list|()
expr_stmt|;
block|}
annotation|@
name|After
specifier|public
name|void
name|stopBroker
parameter_list|()
throws|throws
name|Exception
block|{
name|brokerService
operator|.
name|stop
argument_list|()
expr_stmt|;
name|brokerService
operator|.
name|waitUntilStopped
argument_list|()
expr_stmt|;
block|}
specifier|protected
name|void
name|initPersistence
parameter_list|(
name|BrokerService
name|brokerService
parameter_list|)
throws|throws
name|IOException
block|{
name|storeDir
operator|=
name|tempTestDir
operator|.
name|getRoot
argument_list|()
expr_stmt|;
name|brokerService
operator|.
name|setPersistent
argument_list|(
literal|true
argument_list|)
expr_stmt|;
comment|// setup multi-kaha adapter
name|MultiKahaDBPersistenceAdapter
name|persistenceAdapter
init|=
operator|new
name|MultiKahaDBPersistenceAdapter
argument_list|()
decl_stmt|;
name|persistenceAdapter
operator|.
name|setDirectory
argument_list|(
name|storeDir
argument_list|)
expr_stmt|;
name|KahaDBPersistenceAdapter
name|kahaStore
init|=
operator|new
name|KahaDBPersistenceAdapter
argument_list|()
decl_stmt|;
name|kahaStore
operator|.
name|setJournalMaxFileLength
argument_list|(
literal|1024
operator|*
literal|512
argument_list|)
expr_stmt|;
comment|// set up a store per destination
name|FilteredKahaDBPersistenceAdapter
name|filtered
init|=
operator|new
name|FilteredKahaDBPersistenceAdapter
argument_list|()
decl_stmt|;
name|filtered
operator|.
name|setPersistenceAdapter
argument_list|(
name|kahaStore
argument_list|)
expr_stmt|;
name|filtered
operator|.
name|setPerDestination
argument_list|(
literal|true
argument_list|)
expr_stmt|;
name|List
argument_list|<
name|FilteredKahaDBPersistenceAdapter
argument_list|>
name|stores
init|=
operator|new
name|ArrayList
argument_list|<>
argument_list|()
decl_stmt|;
name|stores
operator|.
name|add
argument_list|(
name|filtered
argument_list|)
expr_stmt|;
name|persistenceAdapter
operator|.
name|setFilteredPersistenceAdapters
argument_list|(
name|stores
argument_list|)
expr_stmt|;
name|brokerService
operator|.
name|setPersistenceAdapter
argument_list|(
name|persistenceAdapter
argument_list|)
expr_stmt|;
block|}
comment|/**      * Test that a destination can be deleted and the other destination can still be subscribed to      * @throws Exception      */
annotation|@
name|Test
specifier|public
name|void
name|testDest1Deletion
parameter_list|()
throws|throws
name|Exception
block|{
name|LOG
operator|.
name|info
argument_list|(
literal|"Creating {} first, {} second"
argument_list|,
name|dest1
argument_list|,
name|dest2
argument_list|)
expr_stmt|;
name|LOG
operator|.
name|info
argument_list|(
literal|"Removing {}, subscribing to {}"
argument_list|,
name|dest1
argument_list|,
name|dest2
argument_list|)
expr_stmt|;
comment|// Create two destinations
name|broker
operator|.
name|addDestination
argument_list|(
name|brokerService
operator|.
name|getAdminConnectionContext
argument_list|()
argument_list|,
name|dest1
argument_list|,
literal|false
argument_list|)
expr_stmt|;
name|broker
operator|.
name|addDestination
argument_list|(
name|brokerService
operator|.
name|getAdminConnectionContext
argument_list|()
argument_list|,
name|dest2
argument_list|,
literal|false
argument_list|)
expr_stmt|;
comment|// remove destination2
name|broker
operator|.
name|removeDestination
argument_list|(
name|brokerService
operator|.
name|getAdminConnectionContext
argument_list|()
argument_list|,
name|dest1
argument_list|,
literal|100
argument_list|)
expr_stmt|;
comment|// try and create a consumer on dest2, before AMQ-5875 this
comment|//would cause an IllegalStateException for Topics
name|createConsumer
argument_list|(
name|dest2
argument_list|)
expr_stmt|;
name|Collection
argument_list|<
name|File
argument_list|>
name|storeFiles
init|=
name|FileUtils
operator|.
name|listFiles
argument_list|(
name|storeDir
argument_list|,
operator|new
name|WildcardFileFilter
argument_list|(
literal|"db*"
argument_list|)
argument_list|,
name|getStoreFileFilter
argument_list|()
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
literal|"Store index should still exist"
argument_list|,
name|storeFiles
operator|.
name|size
argument_list|()
operator|>=
literal|1
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testDest2Deletion
parameter_list|()
throws|throws
name|Exception
block|{
name|LOG
operator|.
name|info
argument_list|(
literal|"Creating {} first, {} second"
argument_list|,
name|dest1
argument_list|,
name|dest2
argument_list|)
expr_stmt|;
name|LOG
operator|.
name|info
argument_list|(
literal|"Removing {}, subscribing to {}"
argument_list|,
name|dest2
argument_list|,
name|dest1
argument_list|)
expr_stmt|;
comment|// Create two destinations
name|broker
operator|.
name|addDestination
argument_list|(
name|brokerService
operator|.
name|getAdminConnectionContext
argument_list|()
argument_list|,
name|dest1
argument_list|,
literal|false
argument_list|)
expr_stmt|;
name|broker
operator|.
name|addDestination
argument_list|(
name|brokerService
operator|.
name|getAdminConnectionContext
argument_list|()
argument_list|,
name|dest2
argument_list|,
literal|false
argument_list|)
expr_stmt|;
comment|// remove destination2
name|broker
operator|.
name|removeDestination
argument_list|(
name|brokerService
operator|.
name|getAdminConnectionContext
argument_list|()
argument_list|,
name|dest2
argument_list|,
literal|100
argument_list|)
expr_stmt|;
comment|// try and create a consumer on dest1, before AMQ-5875 this
comment|//would cause an IllegalStateException for Topics
name|createConsumer
argument_list|(
name|dest1
argument_list|)
expr_stmt|;
name|Collection
argument_list|<
name|File
argument_list|>
name|storeFiles
init|=
name|FileUtils
operator|.
name|listFiles
argument_list|(
name|storeDir
argument_list|,
operator|new
name|WildcardFileFilter
argument_list|(
literal|"db*"
argument_list|)
argument_list|,
name|getStoreFileFilter
argument_list|()
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
literal|"Store index should still exist"
argument_list|,
name|storeFiles
operator|.
name|size
argument_list|()
operator|>=
literal|1
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testStoreCleanupDeleteDest1First
parameter_list|()
throws|throws
name|Exception
block|{
name|LOG
operator|.
name|info
argument_list|(
literal|"Creating {} first, {} second"
argument_list|,
name|dest1
argument_list|,
name|dest2
argument_list|)
expr_stmt|;
name|LOG
operator|.
name|info
argument_list|(
literal|"Deleting {} first, {} second"
argument_list|,
name|dest1
argument_list|,
name|dest2
argument_list|)
expr_stmt|;
comment|// Create two destinations
name|broker
operator|.
name|addDestination
argument_list|(
name|brokerService
operator|.
name|getAdminConnectionContext
argument_list|()
argument_list|,
name|dest1
argument_list|,
literal|false
argument_list|)
expr_stmt|;
name|broker
operator|.
name|addDestination
argument_list|(
name|brokerService
operator|.
name|getAdminConnectionContext
argument_list|()
argument_list|,
name|dest2
argument_list|,
literal|false
argument_list|)
expr_stmt|;
comment|// remove both destinations
name|broker
operator|.
name|removeDestination
argument_list|(
name|brokerService
operator|.
name|getAdminConnectionContext
argument_list|()
argument_list|,
name|dest1
argument_list|,
literal|100
argument_list|)
expr_stmt|;
name|broker
operator|.
name|removeDestination
argument_list|(
name|brokerService
operator|.
name|getAdminConnectionContext
argument_list|()
argument_list|,
name|dest2
argument_list|,
literal|100
argument_list|)
expr_stmt|;
comment|//Assert that with no more destinations attached to a store that it has been cleaned up
name|Collection
argument_list|<
name|File
argument_list|>
name|storeFiles
init|=
name|FileUtils
operator|.
name|listFiles
argument_list|(
name|storeDir
argument_list|,
operator|new
name|WildcardFileFilter
argument_list|(
literal|"db*"
argument_list|)
argument_list|,
name|getStoreFileFilter
argument_list|()
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"Store files should be deleted"
argument_list|,
literal|0
argument_list|,
name|storeFiles
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testStoreCleanupDeleteDest2First
parameter_list|()
throws|throws
name|Exception
block|{
name|LOG
operator|.
name|info
argument_list|(
literal|"Creating {} first, {} second"
argument_list|,
name|dest1
argument_list|,
name|dest2
argument_list|)
expr_stmt|;
name|LOG
operator|.
name|info
argument_list|(
literal|"Deleting {} first, {} second"
argument_list|,
name|dest2
argument_list|,
name|dest1
argument_list|)
expr_stmt|;
comment|// Create two destinations
name|broker
operator|.
name|addDestination
argument_list|(
name|brokerService
operator|.
name|getAdminConnectionContext
argument_list|()
argument_list|,
name|dest1
argument_list|,
literal|false
argument_list|)
expr_stmt|;
name|broker
operator|.
name|addDestination
argument_list|(
name|brokerService
operator|.
name|getAdminConnectionContext
argument_list|()
argument_list|,
name|dest2
argument_list|,
literal|false
argument_list|)
expr_stmt|;
comment|// remove both destinations
name|broker
operator|.
name|removeDestination
argument_list|(
name|brokerService
operator|.
name|getAdminConnectionContext
argument_list|()
argument_list|,
name|dest2
argument_list|,
literal|100
argument_list|)
expr_stmt|;
name|broker
operator|.
name|removeDestination
argument_list|(
name|brokerService
operator|.
name|getAdminConnectionContext
argument_list|()
argument_list|,
name|dest1
argument_list|,
literal|100
argument_list|)
expr_stmt|;
comment|//Assert that with no more destinations attached to a store that it has been cleaned up
name|Collection
argument_list|<
name|File
argument_list|>
name|storeFiles
init|=
name|FileUtils
operator|.
name|listFiles
argument_list|(
name|storeDir
argument_list|,
operator|new
name|WildcardFileFilter
argument_list|(
literal|"db*"
argument_list|)
argument_list|,
name|getStoreFileFilter
argument_list|()
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"Store files should be deleted"
argument_list|,
literal|0
argument_list|,
name|storeFiles
operator|.
name|size
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|protected
specifier|abstract
name|void
name|createConsumer
parameter_list|(
name|ActiveMQDestination
name|dest
parameter_list|)
throws|throws
name|JMSException
function_decl|;
specifier|protected
specifier|abstract
name|WildcardFileFilter
name|getStoreFileFilter
parameter_list|()
function_decl|;
block|}
end_class

end_unit

