begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|broker
operator|.
name|region
operator|.
name|cursors
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|broker
operator|.
name|region
operator|.
name|MessageReference
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|broker
operator|.
name|region
operator|.
name|Subscription
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|broker
operator|.
name|region
operator|.
name|Topic
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|command
operator|.
name|Message
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|command
operator|.
name|MessageId
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|filter
operator|.
name|MessageEvaluationContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|filter
operator|.
name|NonCachedMessageEvaluationContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|store
operator|.
name|TopicMessageStore
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|Logger
import|;
end_import

begin_import
import|import
name|org
operator|.
name|slf4j
operator|.
name|LoggerFactory
import|;
end_import

begin_comment
comment|/**  * persist pendingCount messages pendingCount message (messages awaiting dispatch  * to a consumer) cursor  *  *  */
end_comment

begin_class
class|class
name|TopicStorePrefetch
extends|extends
name|AbstractStoreCursor
block|{
specifier|private
specifier|static
specifier|final
name|Logger
name|LOG
init|=
name|LoggerFactory
operator|.
name|getLogger
argument_list|(
name|TopicStorePrefetch
operator|.
name|class
argument_list|)
decl_stmt|;
specifier|private
specifier|final
name|TopicMessageStore
name|store
decl_stmt|;
specifier|private
specifier|final
name|String
name|clientId
decl_stmt|;
specifier|private
specifier|final
name|String
name|subscriberName
decl_stmt|;
specifier|private
specifier|final
name|Subscription
name|subscription
decl_stmt|;
specifier|private
name|byte
name|lastRecoveredPriority
init|=
literal|9
decl_stmt|;
specifier|private
name|boolean
name|storeHasMessages
init|=
literal|false
decl_stmt|;
comment|/**      * @param topic      * @param clientId      * @param subscriberName      */
specifier|public
name|TopicStorePrefetch
parameter_list|(
name|Subscription
name|subscription
parameter_list|,
name|Topic
name|topic
parameter_list|,
name|String
name|clientId
parameter_list|,
name|String
name|subscriberName
parameter_list|)
block|{
name|super
argument_list|(
name|topic
argument_list|)
expr_stmt|;
name|this
operator|.
name|subscription
operator|=
name|subscription
expr_stmt|;
name|this
operator|.
name|store
operator|=
operator|(
name|TopicMessageStore
operator|)
name|topic
operator|.
name|getMessageStore
argument_list|()
expr_stmt|;
name|this
operator|.
name|clientId
operator|=
name|clientId
expr_stmt|;
name|this
operator|.
name|subscriberName
operator|=
name|subscriberName
expr_stmt|;
name|this
operator|.
name|maxProducersToAudit
operator|=
literal|32
expr_stmt|;
name|this
operator|.
name|maxAuditDepth
operator|=
literal|10000
expr_stmt|;
name|resetSize
argument_list|()
expr_stmt|;
name|this
operator|.
name|storeHasMessages
operator|=
name|this
operator|.
name|size
operator|>
literal|0
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|recoverMessageReference
parameter_list|(
name|MessageId
name|messageReference
parameter_list|)
throws|throws
name|Exception
block|{
comment|// shouldn't get called
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"Not supported"
argument_list|)
throw|;
block|}
annotation|@
name|Override
specifier|public
specifier|synchronized
name|void
name|addMessageFirst
parameter_list|(
name|MessageReference
name|node
parameter_list|)
throws|throws
name|Exception
block|{
name|batchList
operator|.
name|addMessageFirst
argument_list|(
name|node
argument_list|)
expr_stmt|;
name|size
operator|++
expr_stmt|;
name|node
operator|.
name|incrementReferenceCount
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
specifier|final
specifier|synchronized
name|boolean
name|addMessageLast
parameter_list|(
name|MessageReference
name|node
parameter_list|)
throws|throws
name|Exception
block|{
name|this
operator|.
name|storeHasMessages
operator|=
name|super
operator|.
name|addMessageLast
argument_list|(
name|node
argument_list|)
expr_stmt|;
return|return
name|this
operator|.
name|storeHasMessages
return|;
block|}
annotation|@
name|Override
specifier|public
specifier|synchronized
name|boolean
name|recoverMessage
parameter_list|(
name|Message
name|message
parameter_list|,
name|boolean
name|cached
parameter_list|)
throws|throws
name|Exception
block|{
name|LOG
operator|.
name|trace
argument_list|(
literal|"{} recover: {}, priority: {}"
argument_list|,
name|this
argument_list|,
name|message
operator|.
name|getMessageId
argument_list|()
argument_list|,
name|message
operator|.
name|getPriority
argument_list|()
argument_list|)
expr_stmt|;
name|boolean
name|recovered
init|=
literal|false
decl_stmt|;
name|MessageEvaluationContext
name|messageEvaluationContext
init|=
operator|new
name|NonCachedMessageEvaluationContext
argument_list|()
decl_stmt|;
name|messageEvaluationContext
operator|.
name|setMessageReference
argument_list|(
name|message
argument_list|)
expr_stmt|;
if|if
condition|(
name|this
operator|.
name|subscription
operator|.
name|matches
argument_list|(
name|message
argument_list|,
name|messageEvaluationContext
argument_list|)
condition|)
block|{
name|recovered
operator|=
name|super
operator|.
name|recoverMessage
argument_list|(
name|message
argument_list|,
name|cached
argument_list|)
expr_stmt|;
if|if
condition|(
name|recovered
operator|&&
operator|!
name|cached
condition|)
block|{
name|lastRecoveredPriority
operator|=
name|message
operator|.
name|getPriority
argument_list|()
expr_stmt|;
block|}
name|storeHasMessages
operator|=
literal|true
expr_stmt|;
block|}
return|return
name|recovered
return|;
block|}
annotation|@
name|Override
specifier|protected
name|boolean
name|duplicateFromStoreExcepted
parameter_list|(
name|Message
name|message
parameter_list|)
block|{
comment|// setBatch is not implemented - sequence order not reliable with concurrent transactions
comment|// on cache exhaustion - first pageIn starts from last ack location which may replay what
comment|// cursor has dispatched
return|return
literal|true
return|;
block|}
annotation|@
name|Override
specifier|protected
specifier|synchronized
name|int
name|getStoreSize
parameter_list|()
block|{
try|try
block|{
return|return
name|store
operator|.
name|getMessageCount
argument_list|(
name|clientId
argument_list|,
name|subscriberName
argument_list|)
return|;
block|}
catch|catch
parameter_list|(
name|Exception
name|e
parameter_list|)
block|{
name|LOG
operator|.
name|error
argument_list|(
literal|"{} Failed to get the outstanding message count from the store"
argument_list|,
name|this
argument_list|,
name|e
argument_list|)
expr_stmt|;
throw|throw
operator|new
name|RuntimeException
argument_list|(
name|e
argument_list|)
throw|;
block|}
block|}
annotation|@
name|Override
specifier|protected
specifier|synchronized
name|long
name|getStoreMessageSize
parameter_list|()
block|{
try|try
block|{
return|return
name|store
operator|.
name|getMessageSize
argument_list|(
name|clientId
argument_list|,
name|subscriberName
argument_list|)
return|;
block|}
catch|catch
parameter_list|(
name|Exception
name|e
parameter_list|)
block|{
name|LOG
operator|.
name|error
argument_list|(
literal|"{} Failed to get the outstanding message count from the store"
argument_list|,
name|this
argument_list|,
name|e
argument_list|)
expr_stmt|;
throw|throw
operator|new
name|RuntimeException
argument_list|(
name|e
argument_list|)
throw|;
block|}
block|}
annotation|@
name|Override
specifier|protected
specifier|synchronized
name|boolean
name|isStoreEmpty
parameter_list|()
block|{
try|try
block|{
return|return
name|this
operator|.
name|store
operator|.
name|isEmpty
argument_list|()
return|;
block|}
catch|catch
parameter_list|(
name|Exception
name|e
parameter_list|)
block|{
name|LOG
operator|.
name|error
argument_list|(
literal|"Failed to determine if store is empty"
argument_list|,
name|e
argument_list|)
expr_stmt|;
throw|throw
operator|new
name|RuntimeException
argument_list|(
name|e
argument_list|)
throw|;
block|}
block|}
annotation|@
name|Override
specifier|protected
name|void
name|resetBatch
parameter_list|()
block|{
name|this
operator|.
name|store
operator|.
name|resetBatching
argument_list|(
name|clientId
argument_list|,
name|subscriberName
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|protected
name|void
name|doFillBatch
parameter_list|()
throws|throws
name|Exception
block|{
comment|// avoid repeated  trips to the store if there is nothing of interest
name|this
operator|.
name|storeHasMessages
operator|=
literal|false
expr_stmt|;
name|this
operator|.
name|store
operator|.
name|recoverNextMessages
argument_list|(
name|clientId
argument_list|,
name|subscriberName
argument_list|,
name|maxBatchSize
argument_list|,
name|this
argument_list|)
expr_stmt|;
name|dealWithDuplicates
argument_list|()
expr_stmt|;
if|if
condition|(
operator|!
name|this
operator|.
name|storeHasMessages
operator|&&
operator|(
operator|!
name|this
operator|.
name|batchList
operator|.
name|isEmpty
argument_list|()
operator|||
operator|!
name|hadSpace
operator|)
condition|)
block|{
name|this
operator|.
name|storeHasMessages
operator|=
literal|true
expr_stmt|;
block|}
block|}
specifier|public
name|byte
name|getLastRecoveredPriority
parameter_list|()
block|{
return|return
name|lastRecoveredPriority
return|;
block|}
specifier|public
specifier|final
name|boolean
name|isPaging
parameter_list|()
block|{
return|return
operator|!
name|isCacheEnabled
argument_list|()
operator|&&
operator|!
name|batchList
operator|.
name|isEmpty
argument_list|()
return|;
block|}
annotation|@
name|Override
specifier|public
name|Subscription
name|getSubscription
parameter_list|()
block|{
return|return
name|subscription
return|;
block|}
annotation|@
name|Override
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
literal|"TopicStorePrefetch("
operator|+
name|clientId
operator|+
literal|","
operator|+
name|subscriberName
operator|+
literal|",storeHasMessages="
operator|+
name|this
operator|.
name|storeHasMessages
operator|+
literal|") "
operator|+
name|this
operator|.
name|subscription
operator|.
name|getConsumerInfo
argument_list|()
operator|.
name|getConsumerId
argument_list|()
operator|+
literal|" - "
operator|+
name|super
operator|.
name|toString
argument_list|()
return|;
block|}
block|}
end_class

end_unit

