begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|filter
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|command
operator|.
name|ActiveMQQueue
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|command
operator|.
name|ActiveMQTopic
import|;
end_import

begin_import
import|import
name|junit
operator|.
name|framework
operator|.
name|TestCase
import|;
end_import

begin_class
specifier|public
class|class
name|DestinationFilterTest
extends|extends
name|TestCase
block|{
specifier|public
name|void
name|testPrefixFilter
parameter_list|()
throws|throws
name|Exception
block|{
name|DestinationFilter
name|filter
init|=
name|DestinationFilter
operator|.
name|parseFilter
argument_list|(
operator|new
name|ActiveMQQueue
argument_list|(
literal|">"
argument_list|)
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
literal|"Filter not parsed well: "
operator|+
name|filter
operator|.
name|getClass
argument_list|()
argument_list|,
name|filter
operator|instanceof
name|PrefixDestinationFilter
argument_list|)
expr_stmt|;
name|System
operator|.
name|out
operator|.
name|println
argument_list|(
name|filter
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
literal|"Filter matched wrong destination type"
argument_list|,
name|filter
operator|.
name|matches
argument_list|(
operator|new
name|ActiveMQTopic
argument_list|(
literal|">"
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testWildcardFilter
parameter_list|()
throws|throws
name|Exception
block|{
name|DestinationFilter
name|filter
init|=
name|DestinationFilter
operator|.
name|parseFilter
argument_list|(
operator|new
name|ActiveMQQueue
argument_list|(
literal|"A.*"
argument_list|)
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
literal|"Filter not parsed well: "
operator|+
name|filter
operator|.
name|getClass
argument_list|()
argument_list|,
name|filter
operator|instanceof
name|WildcardDestinationFilter
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
literal|"Filter matched wrong destination type"
argument_list|,
name|filter
operator|.
name|matches
argument_list|(
operator|new
name|ActiveMQTopic
argument_list|(
literal|"A.B"
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|testCompositeFilter
parameter_list|()
throws|throws
name|Exception
block|{
name|DestinationFilter
name|filter
init|=
name|DestinationFilter
operator|.
name|parseFilter
argument_list|(
operator|new
name|ActiveMQQueue
argument_list|(
literal|"A.B,B.C"
argument_list|)
argument_list|)
decl_stmt|;
name|assertTrue
argument_list|(
literal|"Filter not parsed well: "
operator|+
name|filter
operator|.
name|getClass
argument_list|()
argument_list|,
name|filter
operator|instanceof
name|CompositeDestinationFilter
argument_list|)
expr_stmt|;
name|assertFalse
argument_list|(
literal|"Filter matched wrong destination type"
argument_list|,
name|filter
operator|.
name|matches
argument_list|(
operator|new
name|ActiveMQTopic
argument_list|(
literal|"A.B"
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

