begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  *   * Licensed to the Apache Software Foundation (ASF) under one or more contributor license agreements. See the NOTICE  * file distributed with this work for additional information regarding copyright ownership. The ASF licenses this file  * to You under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the  * License. You may obtain a copy of the License at  *   * http://www.apache.org/licenses/LICENSE-2.0  *   * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on  * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the  * specific language governing permissions and limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|store
operator|.
name|kahadaptor
package|;
end_package

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|kaha
operator|.
name|ListContainer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|kaha
operator|.
name|StoreEntry
import|;
end_import

begin_comment
comment|/**  * Holds information for the subscriber  *   * @version $Revision: 1.10 $  */
end_comment

begin_class
class|class
name|TopicSubContainer
block|{
specifier|private
name|ListContainer
name|listContainer
decl_stmt|;
specifier|private
name|StoreEntry
name|batchEntry
decl_stmt|;
name|TopicSubContainer
parameter_list|(
name|ListContainer
name|container
parameter_list|)
block|{
name|this
operator|.
name|listContainer
operator|=
name|container
expr_stmt|;
block|}
comment|/**      * @return the batchEntry      */
name|StoreEntry
name|getBatchEntry
parameter_list|()
block|{
return|return
name|this
operator|.
name|batchEntry
return|;
block|}
comment|/**      * @param batchEntry the batchEntry to set      */
name|void
name|setBatchEntry
parameter_list|(
name|StoreEntry
name|batchEntry
parameter_list|)
block|{
name|this
operator|.
name|batchEntry
operator|=
name|batchEntry
expr_stmt|;
block|}
comment|/**      * @return the listContainer      */
name|ListContainer
name|getListContainer
parameter_list|()
block|{
return|return
name|this
operator|.
name|listContainer
return|;
block|}
comment|/**      * @param listContainer the listContainer to set      */
name|void
name|setListContainer
parameter_list|(
name|ListContainer
name|container
parameter_list|)
block|{
name|this
operator|.
name|listContainer
operator|=
name|container
expr_stmt|;
block|}
name|void
name|reset
parameter_list|()
block|{
name|batchEntry
operator|=
literal|null
expr_stmt|;
block|}
block|}
end_class

end_unit

