begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  *  * Copyright 2005-2006 The Apache Software Foundation  *  * Licensed under the Apache License, Version 2.0 (the "License");  * you may not use this file except in compliance with the License.  * You may obtain a copy of the License at  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|openwire
operator|.
name|tool
package|;
end_package

begin_import
import|import
name|org
operator|.
name|codehaus
operator|.
name|jam
operator|.
name|JClass
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_comment
comment|/**  *   * @version $Revision$  */
end_comment

begin_class
specifier|public
specifier|abstract
class|class
name|OpenWireCppClassesScript
extends|extends
name|OpenWireClassesScript
block|{
specifier|public
name|Object
name|run
parameter_list|()
block|{
name|filePostFix
operator|=
name|getFilePostFix
argument_list|()
expr_stmt|;
if|if
condition|(
name|destDir
operator|==
literal|null
condition|)
block|{
name|destDir
operator|=
operator|new
name|File
argument_list|(
literal|"../openwire-cpp/src/command"
argument_list|)
expr_stmt|;
block|}
return|return
name|super
operator|.
name|run
argument_list|()
return|;
block|}
specifier|protected
name|String
name|getFilePostFix
parameter_list|()
block|{
return|return
literal|".cpp"
return|;
block|}
comment|/**      * Converts the Java type to a C++ type name      */
specifier|public
name|String
name|toCppType
parameter_list|(
name|JClass
name|type
parameter_list|)
block|{
name|String
name|name
init|=
name|type
operator|.
name|getSimpleName
argument_list|()
decl_stmt|;
if|if
condition|(
name|name
operator|.
name|equals
argument_list|(
literal|"String"
argument_list|)
condition|)
block|{
return|return
literal|"p<string>"
return|;
block|}
elseif|else
if|if
condition|(
name|name
operator|.
name|equals
argument_list|(
literal|"Throwable"
argument_list|)
operator|||
name|name
operator|.
name|equals
argument_list|(
literal|"Exception"
argument_list|)
condition|)
block|{
return|return
literal|"BrokerError"
return|;
block|}
elseif|else
if|if
condition|(
name|name
operator|.
name|equals
argument_list|(
literal|"ByteSequence"
argument_list|)
condition|)
block|{
return|return
literal|"void*"
return|;
block|}
elseif|else
if|if
condition|(
name|name
operator|.
name|equals
argument_list|(
literal|"boolean"
argument_list|)
condition|)
block|{
return|return
literal|"bool"
return|;
block|}
elseif|else
if|if
condition|(
name|name
operator|.
name|endsWith
argument_list|(
literal|"Id"
argument_list|)
condition|)
block|{
return|return
literal|"p<"
operator|+
name|name
operator|+
literal|">"
return|;
block|}
else|else
block|{
return|return
name|name
return|;
block|}
block|}
comment|/**      * Converts the Java type to a C++ default value      */
specifier|public
name|String
name|toCppDefaultValue
parameter_list|(
name|JClass
name|type
parameter_list|)
block|{
return|return
literal|"NULL"
return|;
block|}
block|}
end_class

end_unit

