begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|transport
operator|.
name|ws
package|;
end_package

begin_import
import|import static
name|org
operator|.
name|junit
operator|.
name|Assert
operator|.
name|assertEquals
import|;
end_import

begin_import
import|import
name|org
operator|.
name|junit
operator|.
name|Test
import|;
end_import

begin_class
specifier|public
class|class
name|SocketTest
block|{
annotation|@
name|Test
specifier|public
name|void
name|testStompSocketRemoteAddress
parameter_list|()
block|{
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|transport
operator|.
name|ws
operator|.
name|jetty8
operator|.
name|StompSocket
name|stompSocketJetty8
init|=
operator|new
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|transport
operator|.
name|ws
operator|.
name|jetty8
operator|.
name|StompSocket
argument_list|(
literal|"ws://localhost:8080"
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"ws://localhost:8080"
argument_list|,
name|stompSocketJetty8
operator|.
name|getRemoteAddress
argument_list|()
argument_list|)
expr_stmt|;
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|transport
operator|.
name|ws
operator|.
name|jetty9
operator|.
name|StompSocket
name|stompSocketJetty9
init|=
operator|new
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|transport
operator|.
name|ws
operator|.
name|jetty9
operator|.
name|StompSocket
argument_list|(
literal|"ws://localhost:8080"
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"ws://localhost:8080"
argument_list|,
name|stompSocketJetty9
operator|.
name|getRemoteAddress
argument_list|()
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Test
specifier|public
name|void
name|testMqttSocketRemoteAddress
parameter_list|()
block|{
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|transport
operator|.
name|ws
operator|.
name|jetty8
operator|.
name|MQTTSocket
name|mqttSocketJetty8
init|=
operator|new
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|transport
operator|.
name|ws
operator|.
name|jetty8
operator|.
name|MQTTSocket
argument_list|(
literal|"ws://localhost:8080"
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"ws://localhost:8080"
argument_list|,
name|mqttSocketJetty8
operator|.
name|getRemoteAddress
argument_list|()
argument_list|)
expr_stmt|;
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|transport
operator|.
name|ws
operator|.
name|jetty8
operator|.
name|MQTTSocket
name|mqttSocketJetty9
init|=
operator|new
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|transport
operator|.
name|ws
operator|.
name|jetty8
operator|.
name|MQTTSocket
argument_list|(
literal|"ws://localhost:8080"
argument_list|)
decl_stmt|;
name|assertEquals
argument_list|(
literal|"ws://localhost:8080"
argument_list|,
name|mqttSocketJetty9
operator|.
name|getRemoteAddress
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

