begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  *   * Copyright 2005-2006 The Apache Software Foundation  *   * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with  * the License. You may obtain a copy of the License at  *   * http://www.apache.org/licenses/LICENSE-2.0  *   * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on  * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the  * specific language governing permissions and limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|broker
operator|.
name|jmx
package|;
end_package

begin_import
import|import
name|javax
operator|.
name|management
operator|.
name|openmbean
operator|.
name|CompositeData
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|management
operator|.
name|openmbean
operator|.
name|OpenDataException
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|management
operator|.
name|openmbean
operator|.
name|TabularData
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|broker
operator|.
name|region
operator|.
name|Subscription
import|;
end_import

begin_comment
comment|/**  * @version $Revision: 1.5 $  */
end_comment

begin_class
specifier|public
class|class
name|DurableSubscriptionView
extends|extends
name|SubscriptionView
implements|implements
name|DurableSubscriptionViewMBean
block|{
specifier|protected
name|String
name|subscriptionName
decl_stmt|;
specifier|public
name|DurableSubscriptionView
parameter_list|(
name|Subscription
name|sub
parameter_list|)
block|{
name|super
argument_list|(
name|sub
argument_list|)
expr_stmt|;
name|this
operator|.
name|subscriptionName
operator|=
name|sub
operator|.
name|getConsumerInfo
argument_list|()
operator|.
name|getSubcriptionName
argument_list|()
expr_stmt|;
block|}
comment|/**      * @return name of the durable consumer      */
specifier|public
name|String
name|getSubscriptionName
parameter_list|()
block|{
return|return
name|subscriptionName
return|;
block|}
comment|/**      * Browse messages for this durable subscriber      *       * @return messages      * @throws OpenDataException      */
specifier|public
name|CompositeData
index|[]
name|browse
parameter_list|()
throws|throws
name|OpenDataException
block|{
return|return
literal|null
return|;
block|}
comment|/**      * Browse messages for this durable subscriber      *       * @return messages      * @throws OpenDataException      */
specifier|public
name|TabularData
name|browseAsTable
parameter_list|()
throws|throws
name|OpenDataException
block|{
return|return
literal|null
return|;
block|}
block|}
end_class

end_unit

