begin_unit|revision:0.9.5;language:Java;cregit-version:0.0.1
begin_comment
comment|/**  * Licensed to the Apache Software Foundation (ASF) under one or more  * contributor license agreements.  See the NOTICE file distributed with  * this work for additional information regarding copyright ownership.  * The ASF licenses this file to You under the Apache License, Version 2.0  * (the "License"); you may not use this file except in compliance with  * the License.  You may obtain a copy of the License at  *  *      http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  * See the License for the specific language governing permissions and  * limitations under the License.  */
end_comment

begin_package
package|package
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|transport
operator|.
name|http
package|;
end_package

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|InetSocketAddress
import|;
end_import

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|URI
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|command
operator|.
name|BrokerInfo
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|transport
operator|.
name|SocketConnectorFactory
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|transport
operator|.
name|WebTransportServerSupport
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|transport
operator|.
name|util
operator|.
name|TextWireFormat
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|transport
operator|.
name|xstream
operator|.
name|XStreamWireFormat
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|activemq
operator|.
name|util
operator|.
name|ServiceStopper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jetty
operator|.
name|security
operator|.
name|ConstraintSecurityHandler
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jetty
operator|.
name|server
operator|.
name|Connector
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jetty
operator|.
name|server
operator|.
name|Handler
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jetty
operator|.
name|server
operator|.
name|Server
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jetty
operator|.
name|server
operator|.
name|handler
operator|.
name|HandlerWrapper
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jetty
operator|.
name|servlet
operator|.
name|ServletContextHandler
import|;
end_import

begin_import
import|import
name|org
operator|.
name|eclipse
operator|.
name|jetty
operator|.
name|servlet
operator|.
name|ServletHolder
import|;
end_import

begin_class
specifier|public
class|class
name|HttpTransportServer
extends|extends
name|WebTransportServerSupport
block|{
specifier|private
name|TextWireFormat
name|wireFormat
decl_stmt|;
specifier|private
specifier|final
name|HttpTransportFactory
name|transportFactory
decl_stmt|;
specifier|private
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|wireFormatOptions
init|=
operator|new
name|HashMap
argument_list|<>
argument_list|()
decl_stmt|;
specifier|public
name|HttpTransportServer
parameter_list|(
name|URI
name|uri
parameter_list|,
name|HttpTransportFactory
name|factory
parameter_list|)
block|{
name|super
argument_list|(
name|uri
argument_list|)
expr_stmt|;
name|this
operator|.
name|bindAddress
operator|=
name|uri
expr_stmt|;
name|this
operator|.
name|transportFactory
operator|=
name|factory
expr_stmt|;
name|socketConnectorFactory
operator|=
operator|new
name|SocketConnectorFactory
argument_list|()
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|setBrokerInfo
parameter_list|(
name|BrokerInfo
name|brokerInfo
parameter_list|)
block|{     }
comment|// Properties
comment|// -------------------------------------------------------------------------
specifier|public
name|TextWireFormat
name|getWireFormat
parameter_list|()
block|{
if|if
condition|(
name|wireFormat
operator|==
literal|null
condition|)
block|{
name|wireFormat
operator|=
name|createWireFormat
argument_list|()
expr_stmt|;
block|}
return|return
name|wireFormat
return|;
block|}
specifier|public
name|void
name|setWireFormat
parameter_list|(
name|TextWireFormat
name|wireFormat
parameter_list|)
block|{
name|this
operator|.
name|wireFormat
operator|=
name|wireFormat
expr_stmt|;
block|}
comment|// Implementation methods
comment|// -------------------------------------------------------------------------
specifier|protected
name|TextWireFormat
name|createWireFormat
parameter_list|()
block|{
return|return
operator|new
name|XStreamWireFormat
argument_list|()
return|;
block|}
specifier|protected
name|void
name|setConnector
parameter_list|(
name|Connector
name|connector
parameter_list|)
block|{
name|this
operator|.
name|connector
operator|=
name|connector
expr_stmt|;
block|}
annotation|@
name|Override
specifier|protected
name|void
name|doStart
parameter_list|()
throws|throws
name|Exception
block|{
name|createServer
argument_list|()
expr_stmt|;
if|if
condition|(
name|connector
operator|==
literal|null
condition|)
block|{
name|connector
operator|=
name|socketConnectorFactory
operator|.
name|createConnector
argument_list|(
name|server
argument_list|)
expr_stmt|;
block|}
name|URI
name|boundTo
init|=
name|bind
argument_list|()
decl_stmt|;
name|ServletContextHandler
name|contextHandler
init|=
operator|new
name|ServletContextHandler
argument_list|(
name|server
argument_list|,
literal|"/"
argument_list|,
name|ServletContextHandler
operator|.
name|SECURITY
argument_list|)
decl_stmt|;
name|ServletHolder
name|holder
init|=
operator|new
name|ServletHolder
argument_list|()
decl_stmt|;
name|holder
operator|.
name|setServlet
argument_list|(
operator|new
name|HttpTunnelServlet
argument_list|()
argument_list|)
expr_stmt|;
name|contextHandler
operator|.
name|addServlet
argument_list|(
name|holder
argument_list|,
literal|"/"
argument_list|)
expr_stmt|;
name|contextHandler
operator|.
name|setAttribute
argument_list|(
literal|"acceptListener"
argument_list|,
name|getAcceptListener
argument_list|()
argument_list|)
expr_stmt|;
name|contextHandler
operator|.
name|setAttribute
argument_list|(
literal|"wireFormat"
argument_list|,
name|getWireFormat
argument_list|()
argument_list|)
expr_stmt|;
name|contextHandler
operator|.
name|setAttribute
argument_list|(
literal|"transportFactory"
argument_list|,
name|transportFactory
argument_list|)
expr_stmt|;
name|contextHandler
operator|.
name|setAttribute
argument_list|(
literal|"transportOptions"
argument_list|,
name|transportOptions
argument_list|)
expr_stmt|;
name|contextHandler
operator|.
name|setAttribute
argument_list|(
literal|"wireFormatOptions"
argument_list|,
name|wireFormatOptions
argument_list|)
expr_stmt|;
comment|//AMQ-6182 - disabling trace by default
name|configureTraceMethod
argument_list|(
operator|(
name|ConstraintSecurityHandler
operator|)
name|contextHandler
operator|.
name|getSecurityHandler
argument_list|()
argument_list|,
name|httpOptions
operator|.
name|isEnableTrace
argument_list|()
argument_list|)
expr_stmt|;
name|addGzipHandler
argument_list|(
name|contextHandler
argument_list|)
expr_stmt|;
name|server
operator|.
name|start
argument_list|()
expr_stmt|;
comment|// Update the Connect To URI with our actual location in case the configured port
comment|// was set to zero so that we report the actual port we are listening on.
name|int
name|port
init|=
name|boundTo
operator|.
name|getPort
argument_list|()
decl_stmt|;
name|int
name|p2
init|=
name|getConnectorLocalPort
argument_list|()
decl_stmt|;
if|if
condition|(
name|p2
operator|!=
operator|-
literal|1
condition|)
block|{
name|port
operator|=
name|p2
expr_stmt|;
block|}
name|setConnectURI
argument_list|(
operator|new
name|URI
argument_list|(
name|boundTo
operator|.
name|getScheme
argument_list|()
argument_list|,
name|boundTo
operator|.
name|getUserInfo
argument_list|()
argument_list|,
name|boundTo
operator|.
name|getHost
argument_list|()
argument_list|,
name|port
argument_list|,
name|boundTo
operator|.
name|getPath
argument_list|()
argument_list|,
name|boundTo
operator|.
name|getQuery
argument_list|()
argument_list|,
name|boundTo
operator|.
name|getFragment
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|private
name|int
name|getConnectorLocalPort
parameter_list|()
throws|throws
name|Exception
block|{
return|return
operator|(
name|Integer
operator|)
name|connector
operator|.
name|getClass
argument_list|()
operator|.
name|getMethod
argument_list|(
literal|"getLocalPort"
argument_list|)
operator|.
name|invoke
argument_list|(
name|connector
argument_list|)
return|;
block|}
specifier|private
name|void
name|addGzipHandler
parameter_list|(
name|ServletContextHandler
name|contextHandler
parameter_list|)
throws|throws
name|Exception
block|{
name|HandlerWrapper
name|handler
init|=
literal|null
decl_stmt|;
try|try
block|{
name|handler
operator|=
operator|(
name|HandlerWrapper
operator|)
name|forName
argument_list|(
literal|"org.eclipse.jetty.servlets.gzip.GzipHandler"
argument_list|)
operator|.
name|newInstance
argument_list|()
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Throwable
name|t
parameter_list|)
block|{
name|handler
operator|=
operator|(
name|HandlerWrapper
operator|)
name|forName
argument_list|(
literal|"org.eclipse.jetty.server.handler.gzip.GzipHandler"
argument_list|)
operator|.
name|newInstance
argument_list|()
expr_stmt|;
block|}
name|contextHandler
operator|.
name|insertHandler
argument_list|(
name|handler
argument_list|)
expr_stmt|;
block|}
specifier|private
name|Class
argument_list|<
name|?
argument_list|>
name|forName
parameter_list|(
name|String
name|name
parameter_list|)
throws|throws
name|ClassNotFoundException
block|{
name|Class
argument_list|<
name|?
argument_list|>
name|clazz
init|=
literal|null
decl_stmt|;
name|ClassLoader
name|loader
init|=
name|Thread
operator|.
name|currentThread
argument_list|()
operator|.
name|getContextClassLoader
argument_list|()
decl_stmt|;
if|if
condition|(
name|loader
operator|!=
literal|null
condition|)
block|{
try|try
block|{
name|clazz
operator|=
name|loader
operator|.
name|loadClass
argument_list|(
name|name
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|ClassNotFoundException
name|e
parameter_list|)
block|{
comment|// ignore
block|}
block|}
if|if
condition|(
name|clazz
operator|==
literal|null
condition|)
block|{
name|clazz
operator|=
name|HttpTransportServer
operator|.
name|class
operator|.
name|getClassLoader
argument_list|()
operator|.
name|loadClass
argument_list|(
name|name
argument_list|)
expr_stmt|;
block|}
return|return
name|clazz
return|;
block|}
annotation|@
name|Override
specifier|protected
name|void
name|doStop
parameter_list|(
name|ServiceStopper
name|stopper
parameter_list|)
throws|throws
name|Exception
block|{
name|Server
name|temp
init|=
name|server
decl_stmt|;
name|server
operator|=
literal|null
expr_stmt|;
if|if
condition|(
name|temp
operator|!=
literal|null
condition|)
block|{
name|temp
operator|.
name|stop
argument_list|()
expr_stmt|;
block|}
block|}
annotation|@
name|Override
specifier|public
name|InetSocketAddress
name|getSocketAddress
parameter_list|()
block|{
return|return
literal|null
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|setTransportOption
parameter_list|(
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|transportOptions
parameter_list|)
block|{
name|socketConnectorFactory
operator|.
name|setTransportOptions
argument_list|(
name|transportOptions
argument_list|)
expr_stmt|;
name|super
operator|.
name|setTransportOption
argument_list|(
name|transportOptions
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|setWireFormatOptions
parameter_list|(
name|Map
argument_list|<
name|String
argument_list|,
name|Object
argument_list|>
name|wireFormatOptions
parameter_list|)
block|{
name|this
operator|.
name|wireFormatOptions
operator|=
name|wireFormatOptions
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|isSslServer
parameter_list|()
block|{
return|return
literal|false
return|;
block|}
block|}
end_class

end_unit

